### ISSUE TITLE
in_array() expects paramter 2 to be array, string given

### ISSUE THREAD

**Issue by opheliadesign** [GeneaLabs/laravel-caffeine#23]
Experiencing this issue after the latest updated. Laravel 5.2:
```
exception 'ErrorException' with message 'in_array() expects parameter 2 to be array, string given' 
in /home/vagrant/fvrs-v2/vendor/genealabs/laravel-caffeine/src/Http/routes.php:18
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'in_array() expe...', '/home/vagrant/f...', 18, Array)
#1 /home/vagrant/fvrs-v2/vendor/genealabs/laravel-caffeine/src/Http/routes.php(18): in_array('web', 'web')
#2 /home/vagrant/fvrs-v2/vendor/genealabs/laravel-caffeine/src/Http/routes.php(5): hasWebMiddleware()
#3 /home/vagrant/fvrs-v2/vendor/genealabs/laravel-caffeine/src/LaravelCaffeineServiceProvider.php(12): require('/home/vagrant/f...')
#4 [internal function]: GeneaLabs\LaravelCaffeine\LaravelCaffeineServiceProvider->boot()
#5 /home/vagrant/fvrs-v2/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#6 /home/vagrant/fvrs-v2/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->call(Array)
#7 /home/vagrant/fvrs-v2/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(717): Illuminate\Foundation\Application->bootProvider(Object(GeneaLabs\LaravelCaffeine\LaravelCaffeineServiceProvider))
#8 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(GeneaLabs\LaravelCaffeine\LaravelCaffeineServiceProvider), 20)
#9 /home/vagrant/fvrs-v2/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(718): array_walk(Array, Object(Closure))
#10 /home/vagrant/fvrs-v2/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#11 /home/vagrant/fvrs-v2/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#12 /home/vagrant/fvrs-v2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(232): Illuminate\Foundation\Application->bootstrapWith(Array)
#13 /home/vagrant/fvrs-v2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(127): Illuminate\Foundation\Http\Kernel->bootstrap()
#14 /home/vagrant/fvrs-v2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#15 /home/vagrant/fvrs-v2/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#16 {main}
```

**Comment by mikebronner** [comment]
Hopefully fixed in version 0.3.5.
